name: First workflow
on: push
jobs:
    tets-job:
        runs-on: ubuntu-latest
        steps:
            - name: test job welcome message
              run: echo "Executing the first job"
            - name: readme file content
              run: cat README.md